name: Continuous integration
on: [push, pull_request]
jobs:
  Runner:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node-version: [10, 12, 14]
    steps:
    - name: Checkout Git Source
      uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: |
        npm install
    - name: Continuous integration
      run: npm run ci
